import { PrismaClient, SourceType, WaterAccess } from "@prisma/client";
const prisma = new PrismaClient();
const mockSource = "Synthetic prototype data — not an official government status.";

async function main() {
  await prisma.auditLog.deleteMany(); await prisma.aIInteraction.deleteMany(); await prisma.journeyStep.deleteMany(); await prisma.journey.deleteMany(); await prisma.notification.deleteMany(); await prisma.damageAssessment.deleteMany(); await prisma.damageReport.deleteMany(); await prisma.insurancePolicy.deleteMany(); await prisma.applicationStatus.deleteMany(); await prisma.application.deleteMany(); await prisma.benefitMatch.deleteMany(); await prisma.documentRequirement.deleteMany(); await prisma.schemeEligibilityRule.deleteMany(); await prisma.scheme.deleteMany(); await prisma.marketPrice.deleteMany(); await prisma.market.deleteMany(); await prisma.waterData.deleteMany(); await prisma.cropSeason.deleteMany(); await prisma.farm.deleteMany(); await prisma.crop.deleteMany(); await prisma.farmerProfile.deleteMany(); await prisma.user.deleteMany();

  const crops = await Promise.all(["Paddy","Groundnut","Millets","Cotton","Sugarcane","Maize","Banana","Vegetables","Pulses"].map((name) => prisma.crop.create({ data: { name, category: name === "Vegetables" ? "Horticulture" : "Field crop", waterNeed: ["Paddy","Banana","Sugarcane"].includes(name) ? "High" : name === "Groundnut" || name === "Millets" || name === "Pulses" ? "Low" : "Moderate" } })));
  const cropByName = Object.fromEntries(crops.map((crop) => [crop.name, crop]));
  const user = await prisma.user.create({ data: { email: "demo@uzhavan.local", role: "FARMER", isDemo: true, farmerProfile: { create: { fullName: "Arun Kumar", stateCode: "TN", stateName: "Tamil Nadu", district: "Thanjavur", waterAccess: WaterAccess.LIMITED, source: mockSource, farms: { create: { name: "Arun's Demo Farm", acreage: 2, irrigation: "Borewell + rain", village: "Synthetic Thanjavur village", soilType: "Alluvial", cropSeasons: { create: { cropId: cropByName.Paddy.id, season: "Kharif", year: 2026, status: "PREVIOUS" } }, waterData: { create: { status: "LIMITED", notes: "Synthetic water availability for the demo.", source: mockSource } } } } } } } });
  const profile = await prisma.farmerProfile.findUniqueOrThrow({ where: { userId: user.id } });
  const schemes = await Promise.all([
    ["MOCK-PMFBY", "Crop Protection Support", "Simulated insurance-support pathway for seasonal crops.", "Insurance", null, "Central Government prototype reference", SourceType.CENTRAL],
    ["MOCK-MACH", "Farm Equipment Support", "Simulated machinery support pathway. Verification is required.", "Machinery", null, "Central Government prototype reference", SourceType.CENTRAL],
    ["MOCK-TN-IRR", "Tamil Nadu Water-Efficient Farming Support", "Simulated support pathway for farms managing limited water.", "Irrigation", "TN", "Tamil Nadu Agriculture Department prototype reference", SourceType.STATE],
    ["MOCK-TN-INPUT", "Tamil Nadu Seasonal Input Support", "Simulated crop input support pathway for eligible farmers.", "Input support", "TN", "Tamil Nadu Agriculture Department prototype reference", SourceType.STATE]
  ].map(([code, name, description, category, stateCode, source, sourceType]) => prisma.scheme.create({ data: { code: code as string, name: name as string, description: description as string, category: category as string, stateCode: stateCode as string | null, source: source as string, sourceType: sourceType as SourceType, sourceUpdatedAt: new Date("2026-01-01") } })));
  for (const scheme of schemes) { await prisma.schemeEligibilityRule.create({ data: { schemeId: scheme.id, ruleType: "state", ruleValue: scheme.stateCode ?? "ALL" } }); await prisma.documentRequirement.create({ data: { schemeId: scheme.id, title: "Farm profile summary", description: "Generated from this synthetic demo profile." } }); await prisma.benefitMatch.create({ data: { farmerProfileId: profile.id, schemeId: scheme.id, score: scheme.code.includes("IRR") ? 94 : 78, rationale: "Potentially relevant based on this synthetic farm profile." } }); }
  const application = await prisma.application.create({ data: { userId: user.id, schemeId: schemes[2].id, state: "DOCUMENTS_REQUIRED", referenceCode: "DEMO-TN-2026-001", isMock: true } }); await prisma.applicationStatus.create({ data: { applicationId: application.id, state: "DOCUMENTS_REQUIRED", message: "Demo application: review the simulated document checklist.", isCurrent: true } });
  await prisma.insurancePolicy.create({ data: { farmerProfileId: profile.id, providerName: "Prototype crop protection pathway", cropName: "Paddy", status: "CHECK_AVAILABLE", source: mockSource } });
  const damage = await prisma.damageReport.create({ data: { farmerProfileId: profile.id, cropName: "Paddy", incidentType: "Heavy rain", status: "DRAFT" } }); await prisma.damageAssessment.create({ data: { damageReportId: damage.id, severity: "PENDING", notes: "Synthetic demo assessment — not an official assessment." } });
  const market = await prisma.market.create({ data: { name: "Thanjavur Demo Market", district: "Thanjavur", stateCode: "TN" } }); await prisma.marketPrice.create({ data: { marketId: market.id, cropName: "Groundnut", pricePerQuintal: 6200, observedAt: new Date("2026-08-01"), source: mockSource } });
  const journey = await prisma.journey.create({ data: { userId: user.id, name: "Arun's Kharif journey", steps: { create: [{ title: "Plan", description: "Farm context captured", position: 1, state: "COMPLETE" }, { title: "Benefits", description: "Potential support matched", position: 2, state: "CURRENT" }, { title: "Protect", description: "Check crop protection", position: 3, state: "LOCKED" }, { title: "Grow", description: "Season guidance", position: 4, state: "LOCKED" }, { title: "Sell", description: "Compare market options", position: 5, state: "LOCKED" }] } } });
  await prisma.notification.create({ data: { userId: user.id, title: "Your demo is ready", body: "Your farm and potential support pathways use fictional data." } });
  console.log(`Seeded ${crops.length} crops, ${schemes.length} mock schemes, and journey ${journey.id}.`);
}
main().then(() => prisma.$disconnect()).catch(async (error) => { console.error(error); await prisma.$disconnect(); process.exit(1); });
